version: "3.2"
services:
  statistics:
    build: .
    ports:
      - "5000:5000"
    environment:
      - "REACT_APP_HOSTNAME=172.17.0.1"
      - "REACT_APP_REALM_NAME=docker-monitor-health-server"
      - "REACT_APP_CLIENT_ID=app"
